services:
  # Node.js + Express APIサーバー
  app:
    build: .
    container_name: inventory-app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=inventory_db
      - DB_USER=root
      - DB_PASSWORD=password
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped

  # MySQL データベース
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=inventory_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --skip-character-set-client-handshake
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  # phpMyAdmin (開発時のDB管理画面)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: inventory-phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: unless-stopped

volumes:
  mysql_data: